apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-dev
  labels:
    app: frontend-service
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: frontend
