apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-dev
  labels:
    app: backend-service
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: backend
  type: NodePort

